# Generated by Django 4.2.9 on 2024-03-25 10:20

from django.db import migrations, models
import django.db.models.deletion
import infrastructure.place.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifyExtra',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('public_name', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('only_developers', models.BooleanField(default=False)),
                ('user_visible', models.CharField(blank=True, max_length=255, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=8)),
                ('icon', models.CharField(default='bookmark', max_length=20)),
                ('pixel_excel', models.IntegerField(default=120)),
                ('settings', models.JSONField(default=dict, verbose_name='Configuración adicional')),
            ],
            options={
                'verbose_name': 'Clasificación de Extras',
                'verbose_name_plural': 'Clasificaciones de Extras',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('params', models.JSONField(blank=True, default=infrastructure.place.models.default_params, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('classify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xtra.classifyextra')),
                ('flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flow.flow')),
            ],
            options={
                'verbose_name': 'Variable Extra',
                'verbose_name_plural': 'Variables Extra',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('public_name', models.CharField(blank=True, max_length=80, null=True)),
                ('javascript_name', models.CharField(blank=True, max_length=50, null=True)),
                ('python_name', models.CharField(blank=True, max_length=50, null=True)),
                ('params', models.JSONField(blank=True, default=infrastructure.place.models.default_params, null=True)),
            ],
            options={
                'verbose_name': 'Formato',
                'verbose_name_plural': 'Formatos',
            },
        ),
        migrations.CreateModel(
            name='PresetValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xtra.extra')),
            ],
            options={
                'verbose_name': 'Valor Predefinido de Extras',
                'verbose_name_plural': 'Valores Predefinidos de Extras',
            },
        ),
        migrations.AddField(
            model_name='extra',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xtra.format'),
        ),
        migrations.AddField(
            model_name='extra',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.space'),
        ),
    ]
