# Generated by Django 4.2.9 on 2024-06-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifyextra',
            name='settings',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Configuración adicional'),
        ),
    ]
