# Generated by Django 4.2.9 on 2025-01-06 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xtra', '0002_alter_classifyextra_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xtra.extra'),
        ),
        migrations.AddField(
            model_name='extra',
            name='has_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='extra',
            name='params',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='format',
            name='params',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
