# Generated by Django 4.2.9 on 2024-05-28 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tool', '0001_initial'),
        ('box', '0001_initial'),
        ('service', '0001_initial'),
        ('xtra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Aplicar Función',
                'verbose_name_plural': 'Aplicar Funciones',
            },
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_value', models.TextField(blank=True, null=True)),
                ('is_remove', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False, verbose_name='Borrado')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
            },
        ),
        migrations.CreateModel(
            name='ParamValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('apply_behavior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='assign.applybehavior')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='box.destination')),
                ('fragment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='box.fragment')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.parameter')),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='box.piece')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='box.reply')),
            ],
            options={
                'verbose_name': '    ',
                'verbose_name_plural': 'Valores de Parámetros',
            },
        ),
        migrations.CreateModel(
            name='ConditionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appear', models.BooleanField(default=True, verbose_name='Aparece/Desaparece')),
                ('extra_values', models.JSONField(blank=True, null=True)),
                ('addl_params', models.JSONField(blank=True, null=True)),
                ('extra_exits', models.BooleanField(blank=True, null=True, verbose_name='Existe extra')),
                ('opposite', models.BooleanField(default=False)),
                ('circles', models.ManyToManyField(blank=True, related_name='rules_in', to='xtra.extra')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='box.destination')),
                ('extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='xtra.extra')),
                ('fragment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='box.fragment')),
                ('platforms', models.ManyToManyField(blank=True, to='service.platform', verbose_name='Plataformas')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='box.reply')),
            ],
            options={
                'verbose_name': 'Regla de condición',
                'verbose_name_plural': 'Reglas de condición',
            },
        ),
    ]
