# Generated by Django 4.2.9 on 2024-03-25 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('tool', '0001_initial'),
        ('xtra', '0001_initial'),
        ('place', '0001_initial'),
        ('assign', '0001_initial'),
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionrule',
            name='roles',
            field=models.ManyToManyField(blank=True, to='member.role'),
        ),
        migrations.AddField(
            model_name='assign',
            name='circles',
            field=models.ManyToManyField(blank=True, related_name='assignments_in', to='xtra.extra'),
        ),
        migrations.AddField(
            model_name='assign',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='box.destination'),
        ),
        migrations.AddField(
            model_name='assign',
            name='extra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='xtra.extra'),
        ),
        migrations.AddField(
            model_name='assign',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box.piece'),
        ),
        migrations.AddField(
            model_name='assign',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box.reply'),
        ),
        migrations.AddField(
            model_name='assign',
            name='written',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box.written'),
        ),
        migrations.AddField(
            model_name='applybehavior',
            name='behavior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.behavior'),
        ),
        migrations.AddField(
            model_name='applybehavior',
            name='main_piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_behavior', to='box.piece'),
        ),
        migrations.AddField(
            model_name='applybehavior',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.space'),
        ),
        migrations.AlterUniqueTogether(
            name='applybehavior',
            unique_together={('behavior', 'space')},
        ),
    ]
