# Generated by Django 4.2.9 on 2024-04-10 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
        ('assign', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applybehavior',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='place.space'),
        ),
    ]
