# Generated by Django 4.2.9 on 2024-05-30 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_alter_destination_piece'),
        ('assign', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditionrule',
            name='opposite',
        ),
        migrations.AddField(
            model_name='conditionrule',
            name='match_all_conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conditionrule',
            name='match_all_rules',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assign',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='box.piece'),
        ),
        migrations.AlterField(
            model_name='assign',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='box.reply'),
        ),
        migrations.AlterField(
            model_name='assign',
            name='written',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='box.written'),
        ),
    ]
