# Generated by Django 4.2.9 on 2024-07-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('assign', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionrule',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='rules_in', to='service.platform', verbose_name='Plataformas'),
        ),
    ]
