# Generated by Django 4.2.9 on 2024-08-30 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        ('assign', '0003_alter_conditionrule_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionrule',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='notification.notification'),
        ),
    ]
