# Generated by Django 4.2.9 on 2024-04-17 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_rename_text_fragment_body_and_more'),
        ('assign', '0003_alter_applybehavior_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramvalue',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='box.piece'),
        ),
        migrations.AlterField(
            model_name='paramvalue',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='box.reply'),
        ),
    ]
