# Generated by Django 4.2.9 on 2024-07-11 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0002_alter_account_platform_alter_account_space'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('media_type', models.CharField(choices=[('image', 'image'), ('video', 'video'), ('audio', 'audio'), ('file', 'file'), ('document', 'document'), ('sticker', 'sticker')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('media_id', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_media_id_at', models.DateTimeField(blank=True, null=True)),
                ('expiration_days', models.IntegerField(default=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.account')),
            ],
        ),
    ]
