# Generated by Django 4.2.9 on 2024-07-19 02:23

from django.db import migrations, models
import infrastructure.persistent_media.models


class Migration(migrations.Migration):

    dependencies = [
        ('persistent_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=infrastructure.persistent_media.models.get_media_path),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video'), ('audio', 'audio'), ('document', 'document'), ('sticker', 'sticker')], max_length=20),
        ),
    ]
