# Generated by Django 4.2.9 on 2026-06-29 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0004_alter_account_app_id'),
        ('persistent_media', '0002_alter_media_file_alter_media_media_type'),
        ('member', '0005_memberaccount_interest_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=30, unique=True)),
                ('tipo_contrato', models.CharField(choices=[('planta', 'De planta'), ('entrada_salida', 'Entrada por salida')], max_length=20)),
                ('trab_nombre', models.CharField(max_length=180)),
                ('empl_nombre', models.CharField(max_length=180)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.account')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persistent_media.media')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
