# Generated by Django 4.2.9 on 2024-05-28 18:41

from django.db import migrations, models
import django.db.models.deletion
import infrastructure.service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('public_name', models.CharField(blank=True, max_length=120, null=True)),
                ('way', models.CharField(choices=[('in', 'entrada'), ('out', 'salida'), ('inout', 'inout')], max_length=5)),
                ('group_type', models.CharField(blank=True, choices=[('interactive', 'Interactivo'), ('text', 'Texto escrito'), ('reply_button', 'Botón de respuesta'), ('media', 'Media'), ('event', 'Eventos y Reacciones'), ('special', 'Especial'), ('references', 'Referencias'), ('other', 'Otros')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de interacción',
                'verbose_name_plural': 'Tipos de interacción',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='Nombre clave (fijo)')),
                ('public_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre público')),
                ('description', models.TextField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=infrastructure.service.models.default_dict, verbose_name='Configuración adicional')),
                ('with_users', models.BooleanField(default=True, verbose_name='Tiene usuarios')),
                ('id_field', models.CharField(blank=True, max_length=120, null=True, verbose_name='Campo de id')),
                ('internal', models.BooleanField(default=False, verbose_name='Es de Yeeko')),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='platform')),
                ('config_by_member', models.BooleanField(default=False, verbose_name='Configuración por integrante')),
            ],
            options={
                'verbose_name': 'Plataforma con API e interacción',
                'verbose_name_plural': 'Plataformas con API e interacción',
            },
        ),
        migrations.CreateModel(
            name='ApiRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.JSONField()),
                ('is_incoming', models.BooleanField(default=True)),
                ('response_status', models.SmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True, null=True)),
                ('errors', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('datetime', models.IntegerField(blank=True, null=True)),
                ('interaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.interactiontype')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.platform')),
                ('repeated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.apirecord')),
            ],
        ),
    ]
