# Generated by Django 4.2.9 on 2024-04-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fragment',
            old_name='text',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='fragment',
            name='destination_header',
        ),
        migrations.RemoveField(
            model_name='fragment',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='fragment',
            name='title',
        ),
        migrations.AddField(
            model_name='fragment',
            name='fragment_type',
            field=models.CharField(blank=True, choices=[('message', 'Mensaje'), ('behavior', 'Función Behavior'), ('embedded', 'Pieza embebida')], max_length=20, null=True),
        ),
    ]
