# Generated by Django 4.2.9 on 2024-06-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_remove_reply_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_section',
            field=models.BooleanField(default=False),
        ),
    ]
