# Generated by Django 4.2.9 on 2024-06-05 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_reply_is_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='is_section',
            new_name='is_header_section',
        ),
    ]
