# Generated by Django 4.2.9 on 2024-07-11 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persistent_media', '0001_initial'),
        ('box', '0005_piece_piece_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragment',
            name='persistent_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persistent_media.media'),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='fragment_type',
            field=models.CharField(blank=True, choices=[('message', 'Mensaje'), ('behavior', 'Función Behavior'), ('embedded', 'Pieza embebida'), ('media', 'Persistent Multimedia')], max_length=20, null=True),
        ),
    ]
