# Generated by Django 4.2.9 on 2024-07-20 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_account_app_id'),
        ('box', '0006_fragment_persistent_media_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('APPROVED', 'Aprobado'), ('IN_APPEAL', 'En apelación'), ('PENDING', 'Pendiente'), ('REJECTED', 'Rechazado'), ('PENDING_DELETION', 'Pendiente de eliminación'), ('DELETED', 'Eliminado'), ('DISABLED', 'Desactivado'), ('PAUSED', 'Pausado'), ('LIMIT_EXCEEDED', 'Límite excedido')], default='PENDING', max_length=20)),
                ('category', models.CharField(blank=True, max_length=80, null=True)),
                ('language', models.CharField(default='es_MX', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('raw_template', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.account')),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box.piece')),
            ],
        ),
    ]
