# Generated by Django 4.2.9 on 2024-07-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0007_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='piece_type',
            field=models.CharField(choices=[('content', 'Contenido'), ('destinations', 'Para Destinos'), ('read_only', 'Solo lectura')], default='content', max_length=20),
        ),
        migrations.AlterField(
            model_name='template',
            name='raw_template',
            field=models.JSONField(default=dict),
        ),
    ]
