# Generated by Django 4.2.9 on 2024-07-25 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_account_app_id'),
        ('box', '0009_reply_reply_type_alter_piece_piece_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Template',
            new_name='Platform_Template',
        ),
    ]
