# Generated by Django 4.2.9 on 2024-07-25 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_account_app_id'),
        ('box', '0010_rename_template_platform_template'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Platform_Template',
            new_name='PlatformTemplate',
        ),
    ]
