# Generated by Django 4.2.9 on 2024-07-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0011_rename_platform_template_platformtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformtemplate',
            name='language',
            field=models.CharField(blank=True, default='es_MX', max_length=10, null=True),
        ),
    ]
