# Generated by Django 4.2.9 on 2024-07-31 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xtra', '0002_alter_classifyextra_settings'),
        ('box', '0012_alter_platformtemplate_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformtemplate',
            name='piece',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template', to='box.piece'),
        ),
        migrations.CreateModel(
            name='TemplateParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xtra.extra')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='box.platformtemplate')),
            ],
        ),
    ]
