# Generated by Django 4.2.9 on 2024-08-03 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xtra', '0002_alter_classifyextra_settings'),
        ('box', '0014_templateparameter_component_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateparameter',
            name='extra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xtra.extra'),
        ),
    ]
