# Generated by Django 4.2.9 on 2024-08-20 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        ('box', '0015_alter_templateparameter_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='notification.notification'),
        ),
    ]
