# Generated by Django 4.2.9 on 2024-05-31 07:53

from django.db import migrations, models
import django.db.models.deletion
import infrastructure.member.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('config', models.JSONField(blank=True, default=infrastructure.member.models.default_params, null=True)),
            ],
            options={
                'verbose_name': 'Configuración de Autenticación',
                'verbose_name_plural': 'Configuraciones de Autenticación',
            },
        ),
        migrations.CreateModel(
            name='Chrono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checking_lapse', models.IntegerField(blank=True, null=True)),
                ('last_notify', models.DateTimeField(blank=True, null=True)),
                ('checking_date', models.DateTimeField(blank=True, null=True)),
                ('interest_degree', models.IntegerField(blank=True, default=60)),
                ('interest_current', models.IntegerField(blank=True, default=60)),
            ],
            options={
                'verbose_name': 'Crono para notificación',
                'verbose_name_plural': 'Cronos para notificaciones',
            },
        ),
        migrations.CreateModel(
            name='InviteExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=80, null=True)),
                ('last_name', models.CharField(blank=True, max_length=80, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('date_invitation', models.DateTimeField(blank=True, null=True)),
                ('date_accepted', models.DateTimeField(blank=True, null=True)),
                ('viewed', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=300, null=True)),
                ('other_data', models.JSONField(blank=True, null=True)),
                ('verified', models.BooleanField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Invitación a Espacio',
                'verbose_name_plural': 'Invitaciones a Espacios',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('subscribed', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Integrantes',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('public_name', models.CharField(blank=True, max_length=50, null=True)),
                ('has_dashboard_access', models.BooleanField(default=False)),
                ('is_tester', models.BooleanField(default=False)),
                ('can_moderate', models.BooleanField(default=False)),
                ('can_admin', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Orden de prioridad del rol')),
            ],
        ),
        migrations.CreateModel(
            name='StatusAttendance',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('public_name', models.CharField(blank=True, max_length=120, null=True)),
                ('color', models.CharField(blank=True, max_length=80, null=True)),
                ('icon', models.CharField(blank=True, max_length=80, null=True)),
                ('show_in_tracking', models.BooleanField(default=False, verbose_name='Mostrar en seguimiento')),
                ('text_response', models.BooleanField(default=True, verbose_name='Respuesta de texto')),
                ('payload_response', models.BooleanField(default=True, verbose_name='Respuesta de payload')),
            ],
            options={
                'verbose_name': 'Status de Atención',
                'verbose_name_plural': 'Status de Atención',
            },
        ),
        migrations.CreateModel(
            name='MemberAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=191, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('config', models.JSONField(blank=True, default=infrastructure.member.models.default_params, null=True)),
                ('last_interaction', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.account')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.statusattendance', verbose_name='Status de Atención')),
            ],
            options={
                'verbose_name': 'Configuración de Member',
                'verbose_name_plural': 'Configuraciones de Member',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.role'),
        ),
        migrations.AddField(
            model_name='member',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.space'),
        ),
    ]
