# Generated by Django 4.2.9 on 2024-03-25 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
        ('place', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inviteextension',
            name='inviter_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inviteextension',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
        migrations.AddField(
            model_name='inviteextension',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.role'),
        ),
        migrations.AddField(
            model_name='inviteextension',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='place.space'),
        ),
        migrations.AddField(
            model_name='chrono',
            name='member_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.memberaccount'),
        ),
        migrations.AddField(
            model_name='authconfig',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.platform'),
        ),
        migrations.AddField(
            model_name='authconfig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
