# Generated by Django 4.2.9 on 2024-07-05 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
        ('member', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberaccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_accounts', to='place.account'),
        ),
    ]
