# Generated by Django 4.2.9 on 2024-08-02 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('member', '0003_alter_memberaccount_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteextension',
            name='phone_error_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.apirecord'),
        ),
    ]
