# Generated by Django 4.2.9 on 2024-08-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_inviteextension_phone_error_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberaccount',
            name='interest_degree',
            field=models.IntegerField(default=60),
        ),
    ]
