# Generated by Django 4.2.9 on 2024-10-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='last_interaction_out_min_time',
            field=models.IntegerField(default=0, help_text='Minutes, Minimum time required between the last exit interaction'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='limit_timing',
            field=models.IntegerField(blank=True, help_text='Limit of times a notification is attempted to be sent, if None, conditioned on the timings queryset length, if is grate than the timings, use the last timing', null=True),
        ),
    ]
