# Generated by Django 4.2.9 on 2024-10-22 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_last_interaction_out_min_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='last_interaction_out_min_time',
            new_name='min_gap_last_interaction_out',
        ),
    ]
