# Generated by Django 4.2.9 on 2024-03-25 10:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('xtra', '0001_initial'),
        ('service', '0001_initial'),
        ('assign', '0001_initial'),
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltReply',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_for_reply', models.BooleanField(default=False)),
                ('is_for_write', models.BooleanField(default=False)),
                ('params', models.JSONField(blank=True, null=True)),
                ('payload', models.TextField(blank=True, null=True, verbose_name='Payload (old)')),
            ],
            options={
                'verbose_name': 'Respuesta construida',
                'verbose_name_plural': 'Respuestas construidas',
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('mid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('is_incoming', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.IntegerField(blank=True, null=True, verbose_name='Timestamp según plataforma')),
                ('raw_payload', models.TextField(blank=True, null=True)),
                ('reference', models.JSONField(blank=True, null=True)),
                ('api_record_in', models.ManyToManyField(blank=True, related_name='api_records_in', to='service.apirecord')),
                ('api_record_out', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_records_out', to='service.apirecord')),
                ('apply_behavior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_behavior', to='assign.applybehavior')),
                ('interaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.interactiontype')),
                ('member_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.memberaccount')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona', to='member.memberaccount')),
            ],
            options={
                'verbose_name': 'Interacción',
                'verbose_name_plural': 'Interacciones',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_direct', models.BooleanField(default=False, help_text='Fue en respuesta clara')),
                ('built_reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talk.builtreply')),
                ('interaction_reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trigger_reply', to='talk.interaction')),
                ('message_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box.messagelink')),
            ],
            options={
                'verbose_name': 'Origen',
                'verbose_name_plural': 'Orígenes',
            },
        ),
        migrations.AddField(
            model_name='interaction',
            name='trigger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction', to='talk.trigger'),
        ),
        migrations.AddField(
            model_name='builtreply',
            name='interaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk.interaction'),
        ),
        migrations.AddField(
            model_name='builtreply',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box.reply'),
        ),
        migrations.CreateModel(
            name='ExtraValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('payload', 'Payload'), ('written', 'Escrito'), ('dictionary', 'Diccionario'), ('assigned', 'Asignado'), ('unknown', 'Desconocido')], max_length=20)),
                ('modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xtra.extra')),
                ('interactions', models.ManyToManyField(blank=True, to='talk.interaction')),
                ('list_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='talk.extravalue')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_values', to='member.member')),
            ],
            options={
                'verbose_name': 'Valor extra',
                'verbose_name_plural': 'Valores extra',
                'ordering': ['-modified'],
                'unique_together': {('extra', 'member', 'list_by')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(choices=[('received', 'received'), ('sent', 'sent'), ('delivered', 'delivered'), ('read', 'read'), ('optin', 'optin'), ('referral', 'referral'), ('failed', 'failed'), ('deleted', 'deleted'), ('warning', 'warning'), ('reaction', 'reaction')], max_length=20)),
                ('timestamp', models.IntegerField(blank=True, null=True)),
                ('emoji', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateTimeField()),
                ('content', models.JSONField(blank=True, null=True)),
                ('api_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.apirecord')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk.interaction')),
            ],
            options={
                'verbose_name': 'Evento de interacción',
                'verbose_name_plural': 'Eventos de interacción',
                'unique_together': {('event_name', 'interaction', 'emoji')},
            },
        ),
    ]
