# Generated by Django 4.2.9 on 2024-07-09 03:04

from django.db import migrations, models
import infrastructure.talk.models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='raw_payload',
            new_name='raw_data_in',
        ),
        migrations.AddField(
            model_name='interaction',
            name='media_in',
            field=models.FileField(blank=True, null=True, upload_to=infrastructure.talk.models.get_media_in_upload_path),
        ),
    ]
