# Generated by Django 4.2.9 on 2024-04-20 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_rename_text_fragment_body_and_more'),
        ('talk', '0002_alter_builtreply_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='fragment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box.fragment'),
        ),
    ]
