# Generated by Django 4.2.9 on 2024-07-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0002_rename_raw_payload_interaction_raw_data_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='media_in_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
