# Generated by Django 4.2.9 on 2024-08-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0003_interaction_media_in_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
