# Generated by Django 4.2.9 on 2024-08-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0004_interaction_raw_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
