# Generated by Django 4.2.9 on 2024-08-07 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
        ('box', '0015_alter_templateparameter_extra'),
        ('talk', '0005_alter_interaction_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='behavior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.behavior'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trigger_reply', to='box.platformtemplate'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='written',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trigger_reply', to='box.written'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='built_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trigger_reply', to='talk.builtreply'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='message_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trigger_reply', to='box.messagelink'),
        ),
    ]
