# Generated by Django 4.2.9 on 2024-08-20 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_memberaccount_interest_degree'),
        ('notification', '0001_initial'),
        ('talk', '0006_trigger_behavior_trigger_template_trigger_written_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trigger_reply', to='notification.notification'),
        ),
        migrations.AlterField(
            model_name='extravalue',
            name='origin',
            field=models.CharField(choices=[('payload', 'Payload'), ('written', 'Escrito'), ('dictionary', 'Diccionario'), ('assigned', 'Asignado'), ('notification', 'Notificación'), ('unknown', 'Desconocido')], max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sent', models.DateTimeField(auto_now=True)),
                ('next_at', models.DateTimeField(blank=True, null=True)),
                ('actual_timing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_timings', to='notification.notificationtiming')),
                ('controller', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='controller', to='talk.extravalue')),
                ('member_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.memberaccount')),
                ('next_timing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_timings', to='notification.notificationtiming')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notification')),
                ('parameters', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='talk.extravalue')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
