# Generated by Django 4.2.9 on 2025-01-06 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_memberaccount_interest_degree'),
        ('talk', '0007_trigger_notification_alter_extravalue_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extravalue',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='extravalue',
            name='controller_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talk.extravalue'),
        ),
        migrations.AlterField(
            model_name='extravalue',
            name='origin',
            field=models.CharField(choices=[('payload', 'Payload'), ('written', 'Escrito'), ('dictionary', 'Diccionario'), ('assigned', 'Asignado'), ('notification', 'Notificación'), ('unknown', 'Desconocido')], default='unknown', max_length=20),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=1)),
                ('active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='member.member')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'unique_together': {('member', 'number')},
            },
        ),
        migrations.AddField(
            model_name='extravalue',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talk.session'),
        ),
    ]
