# Generated by Django 4.2.9 on 2024-07-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_account_platform_alter_account_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='app_id',
            field=models.CharField(blank=True, help_text='Business ID', max_length=191, null=True),
        ),
    ]
