# Generated by Django 4.2.9 on 2024-10-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_account_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='app_id',
            field=models.CharField(blank=True, help_text='whatsapp_Business ID', max_length=191, null=True),
        ),
    ]
